[package]
name = "rt_in_one_weekend"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more = { version = "2.0.1", features = ["full"]}
rand = "0.9.2"
image = "0.25.6"

[lints.clippy]
needless_return = "allow"
